name: etl-pipeline
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2022.4.26=hecd8cb5_0
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - ncurses=6.3=hca72f7f_2
  - openssl=1.1.1p=hca72f7f_0
  - python=3.10.4=hdfd78df_0
  - readline=8.1.2=hca72f7f_1
  - sqlite=3.38.3=h707629a_0
  - tk=8.6.11=h3fd3227_1
  - tzdata=2022a=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=hca72f7f_1
  - zlib=1.2.12=h4dc903c_2
  - pip:
    - beautifulsoup4==4.11.2
    - boto3==1.24.26
    - botocore==1.27.26
    - bs4==0.0.1
    - certifi==2022.6.15
    - charset-normalizer==2.1.0
    - cli-helpers==2.2.1
    - click==8.1.3
    - configobj==5.0.6
    - greenlet==1.1.2
    - humanize==4.2.3
    - idna==3.3
    - jmespath==1.0.1
    - pgspecial==2.0.1
    - pip==21.2.4
    - prompt-toolkit==1.0.18
    - psycopg==3.0.15
    - psycopg2-binary==2.9.3
    - pygments==2.12.0
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - requests==2.28.1
    - s3transfer==0.6.0
    - setproctitle==1.2.3
    - setuptools==61.2.0
    - six==1.16.0
    - soupsieve==2.4
    - sqlalchemy==1.4.39
    - sqlparse==0.2.4
    - tabulate==0.8.10
    - urllib3==1.26.10
    - wcwidth==0.2.5
prefix: /opt/anaconda3/envs/etl-pipeline
